# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- develop

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  gitlabhub: 'Gitlab Tuteria'
  imageName: 'registry.gitlab.com/tuteria/v2/tutor-frontend-app/tutor-application'
  shortName: "tuteria/v2/tutor-frontend-app/tutor-application"


pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'
- task: CopyFiles@2
  inputs:
    SourceFolder: 'production'
    Contents: '.npmrc'
    TargetFolder: '$(Build.SourcesDirectory)'
    OverWrite: true

- script: |
    yarn install
  displayName: 'yarn install dependencies'

- script: |
    yarn test
  displayName: 'yarn test'
  
- task: Docker@2 
  displayName: Build an image
  inputs:
    command: build 
    repository: $(imageName)
    dockerfile: $(Build.SourcesDirectory)/Dockerfile
    tags: |
      $(tag)
    buildContext: $(Build.SourcesDirectory)
- task: Docker@2
  displayName: "Push image to gitlab"
  inputs:
    containerRegistry: |
      $(gitlabhub)
    repository: $(shortName)
    command: push
    tags: |
      $(tag)
  

