# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- develop
- master
- feature/*
- bug/*

resources:
# - repo: self
  repositories: 
    - repository: templates
      type: git 
      name: Tuteria/tuteria-deploy
      ref: refs/heads/develop

pool:
  vmImage: ubuntu-latest

stages:
- template: azure-templates/build-stage.yml@templates
  parameters:
    short_name: "tuteria/v2/tutor-frontend-app/tutor-application"
    tag: $(Build.BuildId)
- template: azure-templates/deploy-all-stages.yml@templates
  parameters:
    short_name: "tuteria/v2/tutor-frontend-app/tutor-application"
    tag: $(Build.BuildId)
