FROM mhart/alpine-node:14

RUN apk update && apk upgrade && \
    apk add --no-cache bash git openssh

WORKDIR /app

COPY . .

RUN mv package-prod.json package.json

RUN yarn install

RUN npm install -g vercel

ARG NOW_TOKEN

RUN vercel --no-clipboard --token=$NOW_TOKEN --prod
# RUN yarn build:next
