FROM mhart/alpine-node:14

RUN apk update && apk upgrade && \
    apk add --no-cache bash git openssh

WORKDIR /app

COPY . .

RUN mv package-prod.json package.json

RUN yarn install

RUN yarn add vercel

ENV NOW_TOKEN "HZT3w9QVx49ajPNviQDd0tDA"

RUN yarn build:next
